// examples/react/src/components/DecryptionDemo.tsx
import { useState } from 'react';
import { useFhevm } from '@fhevm/sdk/react';
import type { FhevmConfig } from '@fhevm/sdk';

interface DecryptionDemoProps {
  config: FhevmConfig;
}

export default function DecryptionDemo({ config }: DecryptionDemoProps) {
  const { decrypt, isLoading } = useFhevm(config);
  const [encryptedValue, setEncryptedValue] = useState('');
  const [contractAddress, setContractAddress] = useState('');
  const [decryptedData, setDecryptedData] = useState<string>('');
  const [error, setError] = useState<string>('');

  const handleDecrypt = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setDecryptedData('');

    try {
      const result = await decrypt(contractAddress, encryptedValue);
      setDecryptedData(result.toString());
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Decryption failed');
    }
  };

  return (
    <div className="card">
      <h2>🔓 Decrypt Data</h2>
      <form onSubmit={handleDecrypt}>
        <div className="form-group">
          <label htmlFor="decrypt-contract">Contract Address</label>
          <input
            id="decrypt-contract"
            type="text"
            className="input"
            value={contractAddress}
            onChange={(e) => setContractAddress(e.target.value)}
            placeholder="0x..."
            required
          />
        </div>

        <div className="form-group">
          <label htmlFor="decrypt-value">Encrypted Value (hex)</label>
          <textarea
            id="decrypt-value"
            className="input"
            value={encryptedValue}
            onChange={(e) => setEncryptedValue(e.target.value)}
            placeholder="0x..."
            rows={4}
            required
            style={{ resize: 'vertical' }}
          />
        </div>

        <button
          type="submit"
          className="button"
          disabled={isLoading || !encryptedValue || !contractAddress}
        >
          {isLoading ? 'Decrypting...' : 'Decrypt'}
        </button>
      </form>

      {error && (
        <div className="error" style={{ marginTop: '16px' }}>
          {error}
        </div>
      )}

      {decryptedData && (
        <div className="success" style={{ marginTop: '16px' }}>
          <strong>Decrypted Value:</strong>
          <div style={{
            marginTop: '8px',
            fontSize: '20px',
            fontWeight: '600'
          }}>
            {decryptedData}
          </div>
        </div>
      )}
    </div>
  );
}

// examples/vue/src/components/DecryptionDemo.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useFhevm } from '@fhevm/sdk/vue';
import type { FhevmConfig } from '@fhevm/sdk';

interface Props {
  config: FhevmConfig;
}

const props = defineProps<Props>();

const { decrypt, isLoading } = useFhevm(props.config);
const encryptedValue = ref('');
const contractAddress = ref('');
const decryptedData = ref('');
const error = ref('');

const handleDecrypt = async () => {
  error.value = '';
  decryptedData.value = '';

  try {
    const result = await decrypt(contractAddress.value, encryptedValue.value);
    decryptedData.value = result.toString();
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Decryption failed';
  }
};
</script>

<template>
  <div class="card">
    <h2>🔓 Decrypt Data</h2>
    <form @submit.prevent="handleDecrypt">
      <div class="form-group">
        <label for="decrypt-contract">Contract Address</label>
        <input
          id="decrypt-contract"
          v-model="contractAddress"
          type="text"
          class="input"
          placeholder="0x..."
          required
        />
      </div>

      <div class="form-group">
        <label for="decrypt-value">Encrypted Value (hex)</label>
        <textarea
          id="decrypt-value"
          v-model="encryptedValue"
          class="input"
          placeholder="0x..."
          rows="4"
          required
          style="resize: vertical"
        />
      </div>

      <button
        type="submit"
        class="button"
        :disabled="isLoading || !encryptedValue || !contractAddress"
      >
        {{ isLoading ? 'Decrypting...' : 'Decrypt' }}
      </button>
    </form>

    <div v-if="error" class="error">
      {{ error }}
    </div>

    <div v-if="decryptedData" class="success">
      <strong>Decrypted Value:</strong>
      <div style="margin-top: 8px; font-size: 20px; font-weight: 600">
        {{ decryptedData }}
      </div>
    </div>
  </div>
</template>
